name: Check bun.lockb diff

on:
  pull_request:
    paths:
      - "bun.lockb"

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup for lockfile diff
        run: |
          git config diff.lockb.textconv bun
          git config diff.lockb.binary true
      - name: Get bun.lockb diff
        id: get-diff
        run: echo "diff=$(git diff origin/${{ github.base_ref }} HEAD -- bun.lockb)" >> $GITHUB_OUTPUT
      - name: Post diff result to PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          gh pr comment $PR_NUMBER --body "## bun.lockb diff
          \`\`\`diff
          ${{ steps.get-diff.outputs.diff }}
          \`\`\`"